_wandb:
    value:
        cli_version: 0.22.0
        e:
            0pl558rn584gji5duv1sbl5ejp8a84nt:
                args:
                    - "3"
                    - "4"
                    - "1"
                codePath: 1D/scripts/test_all.py
                codePathLocal: scripts/test_all.py
                email: bplumrid@vols.utk.edu
                executable: /Library/Frameworks/Python.framework/Versions/3.13/bin/python3
                git:
                    commit: 62d078dfc63da141b837d899b8265cb07fbd5fb0
                    remote: git@github.com:benplumridge/NN_FPN.git
                host: mac149848
                os: macOS-15.7-arm64-arm-64bit-Mach-O
                program: /Users/6zp/Desktop/NN_FPN/1D/scripts/test_all.py
                python: CPython 3.13.7
                root: /Users/6zp/Desktop/NN_FPN/1D
                startedAt: "2025-09-25T00:31:25.997509Z"
                writerId: 0pl558rn584gji5duv1sbl5ejp8a84nt
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
            "4": 3.13.7
            "5": 0.22.0
            "12": 0.22.0
            "13": darwin-arm64
"N":
    value: 3
ablation_idx:
    value: 4
model_idx:
    value: 1
